name: casting_platform
description: "Casting Platform mobile app"

# Prevent publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^1.4.0

  # Image picker for picking profile pictures etc.
  image_picker: ^1.1.2

  # For launching URLs (like opening casting calls in browser)
  url_launcher: ^6.3.1
  email_validator: ^3.0.0
  flutter_svg: ^2.2.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # Uncomment if you want to add images:
  assets:
    - assets/images/

  # Uncomment if you want to use custom fonts (example shown):
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
